name: 'Make DAG'
inputs:
  epoch:
    required: true
  distro:
    required: true
  changed:
    required: true
  rebuild:
    required: true
  distro-versions:
    required: true
  env-versions:
    required: true
  matrix-path:
    required: true
  rev-deps-path:
    required: true
  search-channels:
    required: true

runs:
  using: composite
  steps:
    - id: 'setup-path'
      shell: bash
      run: echo "${{ github.action_path }}/bin/" >> $GITHUB_PATH
    - id: 'dag'
      shell: bash
      env:
        PYTHONPATH: "${{ github.action_path }}/../src/"
      run: |
        cat <<EOF | make-dag.py
        ${{ toJSON(inputs) }}
        EOF
