channels:
- https://packages.qiime2.org/qiime2/2023.7/core/passed
- conda-forge
- bioconda
- defaults
dependencies:
- q2-mystery-stew=2023.7.0
- q2-types=2023.7.0
- q2cli=2023.7.0
- qiime2=2023.7.0
- biom-format=2.1.14
- h5py=3.8.0
- hdf5=1.14.0
- notebook=6.5.5
- numpy=1.24.4
- pandas=1.5.3
- python=3.8
- scikit-bio=0.5.8
- scikit-learn=0.24.1
- scipy=1.10.0
- unifrac=1.3
- unifrac-binaries=1.3.1
- r-base=4.2.2
extras:
  variant_override:
    qiime2_epoch: '2023.9'
