on:
  workflow_call:
    inputs:
      epoch:
        required: true
        type: string
      distro:
        required: true
        type: string
      distro-versions:
        required: true
        type: string
      is-release:
        required: true
        type: string
      pr-ref:
        required: true
        type: string
      seed-environment-key:
        required: true
        type: string
      solved-environment-key:
        required: true
        type: string
      repodata-patches-key:
        required: true
        type: string
      rebuilt-channel-key:
        required: true
        type: string

env:
  distributions_repo: './distributions'
  seed_environment_path: './seed_environment'
  solved_environment_path: './solved_environment'

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.pr-ref }}
          path: ${{ env.distributions_repo }}

      - name: get seed environment
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.seed-environment-key }}
          path: ${{ env.seed_environment_path }}

      - name: get solved environment
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.solved-environment-key }}
          path: ${{ env.solved_environment_path }}

      - name: prep directories
        shell: bash
        run: |
          mkdir -p '${{ env.distributions_repo }}/${{ inputs.epoch }}/${{ inputs.distro }}/staged/'
          mkdir -p '${{ env.distributions_repo }}/${{ inputs.epoch }}/${{ inputs.distro }}/passed/'
          mkdir -p '${{ env.distributions_repo }}/${{ inputs.epoch }}/${{ inputs.distro }}/released/'

      - name: update seed environments (staged)
        uses: qiime2/action-library-packaging/patch-env@beta
        with:
          environment-file: ${{ env.distributions_repo }}/${{ inputs.epoch }}/${{ inputs.distro }}/staged/seed-environment-conda.yml
          mask-environment-file: ${{ env.seed_environment_path }}/seed-environment-conda.yml

      - name: update seed environments (passed)
        shell: bash
        run: |
          cp ${{ env.seed_environment_path}}/* '${{ env.distributions_repo }}/${{ inputs.epoch }}/${{ inputs.distro }}/passed/'

      - name: update seed environments (released)
        if: ${{ inputs.is-release == 'true' }}
        shell: bash
        run: |
          cp ${{ env.seed_environment_path}}/* '${{ env.distributions_repo }}/${{ inputs.epoch }}/${{ inputs.distro }}/released/'

      - name: update solved environments (passed)
        shell: bash
        run: |
          cp ${{ env.solved_environment_path}}/* '${{ env.distributions_repo }}/${{ inputs.epoch }}/${{ inputs.distro }}/passed/'

      - name: update solved environments (released)
        if: ${{ inputs.is-release == 'true' }}
        shell: bash
        run: |
          cp ${{ env.solved_environment_path}}/* '${{ env.distributions_repo }}/${{ inputs.epoch }}/${{ inputs.distro }}/released/'

      - uses: EndBug/add-and-commit@v9
        with:
          message: Update conda environments (${{ inputs.pr-ref }})
          default_author: user_info
          author_name: q2d2
          author_email: q2d2.noreply@gmail.com
          cwd: ${{ env.distributions_repo }}

  notify-library:
    needs: commit-changes
    runs-on: ubuntu-latest
    steps:
      - name: notify library
        uses: qiime2/action-library-packaging/notify-library-distro@beta
        with:
          distro: ${{ inputs.distro }}
          distro-versions: ${{ inputs.distro-version }}
          is-release: ${{ inputs.is-release }}
          patch-instructions-artifact-key: ${{ inputs.repodata-patches-key }}
          rebuilt-channel-artifact-key: ${{ inputs.rebuilt-channel-key }}
