# # Example of workflow trigger for calling workflow (the client).
# name: ci-dev
# on:
#   pull_request:
#     branches: ["dev"]
#   push:
#     branches: ["dev"]
# jobs:
#   ci:
#     uses: qiime2/distributions/.github/workflows/lib-ci-dev.yaml@dev

on:
  workflow_call:
    inputs:
      recipe-path:
        description: "Path to recipe"
        required: false
        default: 'ci/recipe'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: "echo TODO"

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v3

    - name: set up python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q https://github.com/qiime2/q2lint/archive/master.zip
        pip install -q flake8

    - name: run flake8
      run: flake8

    - name: run q2lint
      run: q2lint