name: release-docker
on:
  workflow_dispatch:
    inputs:
      epoch:
        required: true
        type: string
      distro:
        required: true
        type: string

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        containerfiles: |
          ./Dockerfile
        image: ${{ inputs.distro }}
        tags: latest ${{ inputs.epoch }}

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/qiime2
        username: qiime2+q2d2
        password: ${{ secrets.QUAY_IO_REGISTRY_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"